### PR TITLE
Changed the buffer cross to eliminate major friction due to misalignm…

### PR DESCRIPTION
**Pull request by jwhite**
This pull request solves the issue with #110.

Rather than to extend the geometry, I modified the angle in place, and created a lower foot to lessen the bend in the PFTE tube.

### CODE REVIEW

**Comment by whi-tw** [comment]
I've just printed a pair of these to test, as I'm seeing this issue. Haven't gotten them installed yet, but printing required supports, as the ECAS hole is floating. could do with being sloped down to the print surface, so the supports aren't needed.

**Comment by jwhite** [comment]
Yes, I see the issue.  I think I also want to add a bump or something to keep the tube from being pulled in.  This doesn't happen in normal use, but it can slip forward when plugging and unplugging.

**Comment by jwhite** [comment]
@whi-tw I improved my design here : https://github.com/EtteGit/EnragedRabbitProject/pull/156 to print without supports and a better alignment method.  Also the mod by @NameOfTheDragon is included, reducing friction even more.

I'm obsoleting this one.

**Comment by jwhite** [comment]
closed due to v2.0

**Pull request closed without merging**
