### PR TITLE
Files for friction fix v2.

### PR DESCRIPTION
**Pull request by jwhite**
This is a pull request that includes v2.0 of the no-friction fix that aligns the entry and exit.  This version is vastly superior to the v1.0 version.

It also includes the pull requestion by TimTek that is merged that removes the friction in the buffer wheel.  

Both fixes together are highly recommended, as friction it the enemy of the buffer.

### CODE REVIEW

**Comment by jwhite** [comment]
image

**Comment by miguelangel-nubla** [comment]
[[a]_Low_Profile_Foot.stl](https://github.com/EtteGit/EnragedRabbitProject/pull/156/files#diff-ab84ed684927093f36bee32a06d8bcf03a76c1529f3415054800eaef4623f1f7) printing orientation is wrong

**Comment by kovmarci86** [comment]
I would be so happy to try this but I use the buffer array mod.

**Comment by miguelangel-nubla** [comment]
@kovmarci86 it is compatible, at least with the 40mm version. I have it running mix and match with the originals to compare.

**Comment by jwhite** [comment]
> I would be so happy to try this but I use the buffer array mod.

It is compatible with the buffer array ( I used it with a 2 wide array.)

**Comment by jwhite** [comment]
> [[a]_Low_Profile_Foot.stl](https://github.com/EtteGit/EnragedRabbitProject/pull/156/files#diff-ab84ed684927093f36bee32a06d8bcf03a76c1529f3415054800eaef4623f1f7) printing orientation is wrong

I'm not sure how to orient a stl.  I think all the parts are likely as fusion has left them.

**Comment by jwhite** [comment]
Just a comment now that I have many more hours using this.

With this fix the bottom part is intentionally close to the wheel.  This spreads out the wraps.   

Even with this and the incorporated wheel friction fix I had some issues with friction.  They were sorted by going to a 3mm ID pfte tube (I was using a semi-clear tube that was supposed to be PFTE, but wasn't.)   Interestingly, the tube between the spool and the crossarm was the largest contributor of friction.  The tube from the buffer to the ERCF is fine in my setup.

I'm now getting flawless performance with 5 wraps around the wheel, something I was never able to do before.

I sometimes have the filament escaping a bit, I'm solving that by using the magnetic screens from the buffer array mod.

**Comment by miguelangel-nubla** [comment]
> > [[a]_Low_Profile_Foot.stl](https://github.com/EtteGit/EnragedRabbitProject/pull/156/files#diff-ab84ed684927093f36bee32a06d8bcf03a76c1529f3415054800eaef4623f1f7) printing orientation is wrong
> 
> I'm not sure how to orient a stl. I think all the parts are likely as fusion has left them.

Rotate them before exporting in fusion.

**Comment by whi-tw** [comment]
Giving this a go! Will report back. Don't suppose you'd be able to make a video of the best way to load the wheel with these changes?

**Pull request closed without merging**
